import { Table } from './interfaces/table.interface';

export const TablesData: Table[] = [
  {
    id: 1,
    name: 'F1',
    people: 0,
    drinks: [],
    food: [],
    moneyAmmount: 0,
    position: 'first',
    course: 0,
  },
  {
    id: 2,
    name: 'F2',
    people: 0,
    drinks: [],
    food: [],
    moneyAmmount: 0,
    position: 'first',
    course: 0,
  },
  {
    id: 3,
    name: 'F3',
    people: 0,
    drinks: [],
    food: [],
    moneyAmmount: 0,
    position: 'first',
    course: 0,
  },
  {
    id: 4,
    name: 'F4',
    people: 0,
    drinks: [],
    food: [],
    moneyAmmount: 0,
    position: 'first',
    course: 0,
  },
  {
    id: 5,
    name: 'S1',
    people: 0,
    drinks: [],
    food: [],
    moneyAmmount: 0,
    position: 'second',
    course: 0,
  },
  {
    id: 6,
    name: 'S2',
    people: 0,
    drinks: [],
    food: [],
    moneyAmmount: 0,
    position: 'second',
    course: 0,
  },
  {
    id: 7,
    name: 'S3',
    people: 0,
    drinks: [],
    food: [],
    moneyAmmount: 0,
    position: 'second',
    course: 0,
  },
  {
    id: 7,
    name: 'S4',
    people: 0,
    drinks: [],
    food: [],
    moneyAmmount: 0,
    position: 'second',
    course: 0,
  },
  {
    id: 8,
    name: 'T1',
    people: 0,
    drinks: [],
    food: [],
    moneyAmmount: 0,
    position: 'terrace',
    course: 0,
  },
  {
    id: 9,
    name: 'T2',
    people: 0,
    drinks: [],
    food: [],
    moneyAmmount: 0,
    position: 'terrace',
    course: 0,
  },
  {
    id: 10,
    name: 'T3',
    people: 0,
    drinks: [],
    food: [],
    moneyAmmount: 0,
    position: 'terrace',
    course: 0,
  },
  {
    id: 11,
    name: 'T4',
    people: 0,
    drinks: [],
    food: [],
    moneyAmmount: 0,
    position: 'terrace',
    course: 0,
  },
  {
    id: 12,
    name: 'T5',
    people: 0,
    drinks: [],
    food: [],
    moneyAmmount: 0,
    position: 'terrace',
    course: 0,
  },
  {
    id: 13,
    name: 'T6',
    people: 0,
    drinks: [],
    food: [],
    moneyAmmount: 0,
    position: 'terrace',
    course: 0,
  },
];
